### ISSUE TITLE
Card Hand Compatibility

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#12]
Hi.

Can you add Compatibility to Card Hand?

![image](https://user-images.githubusercontent.com/4999783/196299519-ee38cc89-b2b2-45f3-bea8-84d31a5a2ef7.png)

![image](https://user-images.githubusercontent.com/4999783/196299450-aa7e8fac-7bbe-4b61-97b1-d82b38d23d62.png)

**Comment by mouse0270** [comment]
What do you mean, that looks great. The actual problem is, I don't know how to use cards in foundry... So I have to learn how to do that to be able to fix this. If you could send me a picture of the inspector for this element, I could at least exclude it from being themed until I learn how to use cards.

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/196536617-cfa3eaa7-0fe1-4f20-849f-50c500024ffd.png)

**Comment by mouse0270** [comment]
Perfect, I can exclude `.image-popout.dark` though I am curious why that developer doesn't append their module id as a class. Thats rather odd design to use such generic class names

**Comment by brunocalado** [comment]
> 

He respond issues fast. Maybe request to do that. 

https://gitlab.com/pengrath/hand-mini-bar/-/issues

**Comment by mouse0270** [comment]
Should be resolved in 0.3.8, needs version 1.2.8 of Card Hand Mini Toolbar
